llm: "llama3.2"
scheme: "http"
appPort: "8080"
wvHost: "weaviate.rag.svc.cluster.local"
wvPort: "9035"
ollamaUrl: "http://ollama.rag.svc.cluster.local"
ollamaPort: "11434"
indexName: "Document"
documentsRetrievalNumber: 3
