llm: "llama3.2"
scheme: "http"
appPort: "8080"
wvHost: "rag.weaviate.svc.cluster.local"
wvPort: "9035"
ollamaHost: "rag.ollama.svc.cluster.local"
ollamaPort: "80"
indexName: "Document"
documentsRetrievalNumber: 3
