apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: rag
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      protocol: TCP
