apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: rag
spec:
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.4.5
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
