apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: localhost:32000/ragserver-frontend
          name: frontend
          resources: {}
          env:
            - name: BACKEND_HOST
              value: "backend.rag.svc.cluster.local"
            - name: BACKEND_PORT
              value: "8000"
