name: Checks
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches:
      - main

permissions: read-all

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yaml
    with:
      go-version: 1.23.2
